services:
  app:
    image: ruby:3.3
    command: /bin/sh -c "sleep infinity"
    # Works but doesn't output to console
    # command: /bin/sh -c 'bundle exec jekyll serve --livereload' --path /docs 
    volumes:
      - ./docs:/docs